### ISSUE TITLE
Monogatari.yml not working

### ISSUE THREAD

**Issue by timeshadowrider** [zeekaran/PlexMetaManagerForMonogatari#3]
Would love some help for why this is not working....

  Anime:
    metadata_files:
      - file: config/Monogatari.yml

 | Updating Monogatari                               |
 | Updating season 1 of Monogatari...         |
| Metadata File Error: Season: 1 not found  |

\Plex\Monogatari\S01 - Bakemonogatari\Bakemonogatari -  S01E01 - Hitagi Crab, Part 1.mkv

**Comment by zeekaran** [comment]
This is likely an issue with PMM / your setup, and not an issue with the config files here. You may find more help at the PMM discord.
